[package]
name = "pp8085"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "pp8085"
path = "src/bin.rs"

[lib]
name = "pp8085_lib"
path = "src/lib.rs"

[dependencies]
